TASKS = [
    {
        "id": "task_1",
        "name": "Merchant Account Recovery",
        "description": "Classify a seller dashboard lockout caused by a 2FA device change.",
        "difficulty": "easy",
        "query": "I changed phones and now I cannot log into the seller dashboard because the OTP is going to my old device.",
        "expected_issue": "account_access",
        "valid_solutions": [],
        "requires_resolution": False,
        "requires_escalation": False,
        "requires_clarification": False,
        "max_steps": 3,
    },
    {
        "id": "task_2",
        "name": "Duplicate Charge Triage",
        "description": "Identify a checkout payment issue and recommend safe next steps for a suspected duplicate charge.",
        "difficulty": "medium",
        "query": "My card was charged twice after I retried checkout and I am worried I will be billed again.",
        "expected_issue": "payment_issue",
        "valid_solutions": [
            "check bank hold",
            "avoid repeated retries",
            "wait 24 hours before retrying",
        ],
        "requires_resolution": False,
        "requires_escalation": False,
        "requires_clarification": False,
        "max_steps": 4,
    },
    {
        "id": "task_3",
        "name": "Unauthorized Payment Escalation",
        "description": "Handle a high-risk payment complaint by clarifying the signal, classifying fraud, advising immediate safety steps, and escalating to the fraud team.",
        "difficulty": "hard",
        "query": "I just noticed a payment on my account that I do not recognize and I need help immediately.",
        "expected_issue": "fraud_risk",
        "valid_solutions": [
            "freeze card",
            "review recent orders",
            "change account password",
        ],
        "requires_resolution": False,
        "requires_escalation": True,
        "requires_clarification": True,
        "clarification_response": "I did not place the order, the card is still active, and the charge showed up 10 minutes ago.",
        "escalation_confirmation": "Thank you. Please send this to the fraud team right away.",
        "max_steps": 5,
    },
]
